@extends('layouts.app')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Records Management</p><h1>Catalog records</h1><p class="muted">Manage the selectable entries used during student registration.</p></div></div>
<section class="table-card record-panel"><div class="record-panel-header"><div><h2>Academic cycles</h2><p class="muted">Add school years and semesters manually. Student registration only uses cycles created here.</p></div><form method="POST" action="{{ route('records.cycles.store') }}" class="record-add-form">@csrf<input name="school_year" placeholder="School year, e.g. 2026-2027" pattern="\d{4}-\d{4}" title="Use the format YYYY-YYYY" required><select name="semester_number" required><option value="1">1st Semester</option><option value="2">2nd Semester</option></select><button class="primary-button" type="submit">Add cycle</button></form></div><table><thead><tr><th>School year</th><th>Semester</th></tr></thead><tbody>@forelse($cycles as $cycle)<tr><td>{{ $cycle->school_year }}</td><td>{{ $cycle->semester_number === 1 ? '1st' : '2nd' }} Semester</td></tr>@empty<tr><td colspan="2">No academic cycles yet.</td></tr>@endforelse</tbody></table></section>
<div class="records-grid">
    @foreach(['barangays' => ['Barangays', 'barangay'], 'schools' => ['Schools', 'school'], 'batches' => ['Batches', 'batch'], 'courses' => ['Courses', 'course']] as $collection => [$title, $singular])
    <section class="table-card record-panel"><div class="record-panel-header"><div><h2>{{ $title }}</h2><p class="muted">{{ ${$collection}->count() }} entries</p></div><form method="POST" action="{{ route('records.store') }}" class="record-add-form">@csrf<input type="hidden" name="collection_name" value="{{ $collection }}"><input name="name" placeholder="Add {{ $singular }}" required><button class="primary-button" type="submit">Add</button></form></div><table><thead><tr><th>Name</th><th></th></tr></thead><tbody>@forelse(${$collection} as $option)<tr><td>{{ $option->name }}</td><td class="record-action"><form method="POST" action="{{ route('records.destroy', $option) }}">@csrf @method('DELETE')<button class="text-button" type="submit" onclick="return confirm('Remove this catalog entry? Existing student values will remain unchanged.')">Remove</button></form></td></tr>@empty<tr><td colspan="2">No {{ $collection }} yet.</td></tr>@endforelse</tbody></table></section>
    @endforeach
</div>
@endsection
