@extends('layouts.app')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Payrolls</p><h1>Payroll preparation</h1><p class="muted">Qualified students with complete submitted requirements for the selected cycle.</p></div></div>
<form method="GET" class="timeline-toolbar"><label>School year / semester<select name="cycle_id" onchange="this.form.submit()">@foreach($cycles as $item)<option value="{{ $item->id }}" @selected($cycle?->id === $item->id)>{{ $item->label() }}</option>@endforeach</select></label><label>Payout type<select name="type" onchange="this.form.submit()"><option value="all" @selected($type === 'all')>Initial and renewal</option><option value="initial" @selected($type === 'initial')>Initial payout</option><option value="renewal" @selected($type === 'renewal')>Renewal payout</option></select></label></form>
<div class="payroll-summary"><span><strong>{{ $payrollRows->count() }}</strong> ready for payroll</span><span><strong>{{ $qualifiedCycles->count() }}</strong> manually qualified</span></div>
<div class="table-card"><table><thead><tr><th>Student</th><th>Student ID</th><th>Payout type</th><th>School</th><th>Requirements</th><th>Qualification</th></tr></thead><tbody>
@forelse($payrollRows as $studentCycle) @php($type = $studentCycle->student->payout_track) @php($progress = $studentCycle->requirementProgress($type))<tr><td>{{ $studentCycle->student->full_name }}</td><td>{{ $studentCycle->student->student_id }}</td><td>{{ ucfirst($type) }}</td><td>{{ $studentCycle->school ?: '—' }}</td><td>{{ $progress['complete'] }}/{{ $progress['total'] }} complete</td><td><span class="status-pill qualified">Qualified</span></td></tr>@empty<tr><td colspan="6">No qualified students with complete requirements for this cycle.</td></tr>@endforelse
</tbody></table></div>
@endsection
